### ISSUE TITLE
RT Chat (Ajax Chat) #14 (ERROR)

### ISSUE THREAD

**Issue by ROZBUD** [RevertIT/mybb-rt_chat#7]
Hello,
I installed subject RT Chat on my new MyBB blog; however, I can see in the browser inspection area, the following ERROR message, which related to the file "rt_chat.js":
"**Uncaught SyntaxError: Identifier 'RT_Chat' has already been declared**"

Kindly refer to attached **screenshot**.
Any help will be much appreciated.

![Error RT Chat](https://github.com/RevertIT/mybb-rt_chat/assets/39498289/5b90175e-59f6-4c2d-989a-e9cacb73222f)

**Comment by RevertIT** [comment]
unrelated to the plugin itself.
